//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMultipleInsert.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Email
    {
        [Key]
        public int Id { get; set; }
        public int UserId { get; set; }
        public string EmailAddress { get; set; }
    
        [ForeignKey("UserId")]
        public virtual User User { get; set; }
    }
}
