//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormMultipleInsert.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public User()
        {
            this.Emails = new HashSet<Email>();
        }

        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is requiered")]
        public string Username { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is requiered")]

        public string Password { get; set; }

        public Nullable<bool> IsAdmin { get; set; }
    
        public virtual ICollection<Email> Emails { get; set; }
    }
}
